### ISSUE TITLE
HTSeq - Counts removed from the data release

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/GenomicDataCommons#100]
I think the alternative is to use `STAR - Counts`. Though there are some files that require a token.
See the `manifest` chunk in https://github.com/Bioconductor/GenomicDataCommons/blob/master/vignettes/overview.Rmd

**Comment by seandavi** [comment]
Thanks for closing.

**Comment by bhagwataditya** [comment]
I stumbled into something similar.
Replacing `HTSeq - Counts` with `STAR - Counts` makes it work for me.
```
require(magrittr)
y <- GenomicDataCommons::files()
y %<>% GenomicDataCommons::filter(cases.project.project_id == 'TCGA-BRCA')
y %<>% GenomicDataCommons::filter(type == 'gene_expression')
# y%<>%GenomicDataCommons::filter(analysis.workflow_type == 'HTSeq - Counts')          # this no longer works
y %<>% GenomicDataCommons::filter(analysis.workflow_type == 'STAR - Counts')           # but this does, thankyou
```

**Comment by LiNk-NY** [comment]
Hi Aditya, @bhagwataditya 
HTSeq Counts have been removed. Please see the [data release notes](https://docs.gdc.cancer.gov/Data/Release_Notes/Data_Release_Notes/#data-release-320).

> And what would be these? `STAR - Counts` also returns no results for me.

Did you try the example code in the vignette? 

```r
files() |>
    filter( cases.project.project_id == 'TCGA-BRCA') |> 
    filter( type == 'gene_expression' ) |>
    filter( analysis.workflow_type == 'STAR - Counts')  |>
    manifest() |>
    head()
```

**Comment by bhagwataditya** [comment]
Thank you Marcel :). That seems to work indeed, not sure why I was under the impression yesterday that it didnt. Thankyou very much! Do you know how exactly the STAR counts are generated (STAR is an aligner no, some other program must be used to 
generate the counts)?

**Comment by bhagwataditya** [comment]
Thankyou very much Marcel! That works indeed, I have updated the example for others' reference.
Small question: is there quick function that shows the fields on which filtering can be performed?
Other question: which method has replaced HTSeq for counting aligned reads?

**Comment by LiNk-NY** [comment]
Hi Aditya, @bhagwataditya 
Please use https://support.bioconductor.org for software-use related questions. 

You can use `available_values` : 

```r
> available_values("files", "experimental_strategy")
 [1] "WXS"                         "RNA-Seq"                    
 [3] "Targeted Sequencing"         "Genotyping Array"           
 [5] "miRNA-Seq"                   "Methylation Array"          
 [7] "WGS"                         "Tissue Slide"               
 [9] "Diagnostic Slide"            "Reverse Phase Protein Array"
[11] "ATAC-Seq"                    "scRNA-Seq"                  
[13] "_missing" 
```

See the STAR paper here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3530905/

**Comment by bhagwataditya** [comment]
Thankyou very much!
