### ISSUE TITLE
token not recognized for slicing

### ISSUE THREAD

**Issue by ajggit** [Bioconductor/GenomicDataCommons#107]
I have a valid GDC token for download that I can use at the command line or in the package e.g.

> token = gdc_token()
> transfer("5ad51ec1-3bcf-445b-8a21-2908c818bdbe",token=token)
Rows: 1 Columns: 5                                                                                                                                                                       
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): id, filename, md5, state
dbl (1): size

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
100% [############################################] Time:  0:02:42  36.1 MiB/s 
100% [############################################] Time:  0:00:02   1.7 MiB/s 
Successfully downloaded: 1
   

But if I try requesting a sliced region:

slicing("5ad51ec1-3bcf-445b-8a21-2908c818bdbe",regions="chr17:75000000-76000000",token=token)
Error in slicing("5ad51ec1-3bcf-445b-8a21-2908c818bdbe", regions = "chr17:75000000-76000000",  : 
  missing(token) is not TRUE

So the token doesn't seem to work with the slicing function. Am I missing something obvious?

**Comment by LiNk-NY** [comment]
Hi @ajggit 

Please make sure you are using version 1.19.3 or higher. 
For details see here: https://github.com/Bioconductor/GenomicDataCommons/issues/90

Best,
Marcel
