### ISSUE TITLE
legacy error while running slicing

### ISSUE THREAD

**Issue by SinhaI** [Bioconductor/GenomicDataCommons#111]
Hi,
While running slicing function I am getting an error message.  

`slicing("df80679e-c4d3-487b-934c-fcc782e5d46e",
        regions="chr17:75000000-76000000", 
       token = GDC_TOKEN,
        overwrite = TRUE,
        legacy = FALSE)`

`Error in if (legacy) .Deprecated(msg = paste0("The 'legacy' argument is deprecated.\n",  : 
  the condition has length > 1`

I have a valid token from GDC. 
Thanks for your help.

**Comment by LiNk-NY** [comment]
Thank you for reporting. I will take a look.

**Comment by LiNk-NY** [comment]
Can you try the latest version on GitHub? `1.25.2`? Thank you.

**Comment by SinhaI** [comment]
Hi, after using version 1.25.2 from GitHub now I am getting below error.

`Error in .gdc_post(endpoint = sprintf("slicing/view/%s", uuid), add_headers('Content-type' = "application/json"),  : 
  Not Found (HTTP 404).`

Thanks.

**Comment by LiNk-NY** [comment]
Hi @SinhaI 
Did you see here? 
https://docs.gdc.cancer.gov/API/Users_Guide/BAM_Slicing/#http-error-codes
It looks like the ID cannot be found. 
Are you using a legacy file?

**Comment by SinhaI** [comment]
Hi,
Thanks for your reply. Now the code is working fine for me. I was trying to slice several .bam files. After checking the list I realized that few of the files are transcriptome bam files for which slicing is not working. It's working fine for genomic bam files.

Slicing for genomic bam files was not working while using an earlier version of GenomicDataCommons however it worked fine while using GitHub version 1.25.2.
Thanks.

**Comment by LiNk-NY** [comment]
I am not sure if the transcriptome bam files are slice-able. You could ask the GDC Help Desk : support@nci-gdc.datacommons.io
