### ISSUE TITLE
slicing HTTP410 error

### ISSUE THREAD

**Issue by lmckinno** [Bioconductor/GenomicDataCommons#114]
Hello,

I am trying to use the slicing() function. Running this example:
#'  slicing("df80679e-c4d3-487b-934c-fcc782e5d46e",
#'         regions="chr17:75000000-76000000",
#'         token=gdc_token())

Gives me the error:
Error in .gdc_post(endpoint = sprintf("legacy/slicing/view/%s", uuid),  : 
  Gone (HTTP 410).

Is there any way to fix this? Thanks!

**Comment by LiNk-NY** [comment]
Hi @lmckinno 

The legacy endpoint was deprecated by the GDC. 
https://github.com/Bioconductor/GenomicDataCommons/blob/devel/NEWS.md#new-features
https://docs.gdc.cancer.gov/API/Release_Notes/API_Release_Notes/#v3280

Note. Please update your version of `GenomicDataCommons`
