### ISSUE TITLE
add cases.project.project_id in the manifest

### ISSUE THREAD

**Issue by billila** [Bioconductor/GenomicDataCommons#117]
Hi!
I would like to visualize the `cases.project.project_id` in the ge_manifest to differentiate which images belong to TCGA-OV or TCGA-BRCA. Here's the R code I'm using:

``` r 
library(GenomicDataCommons)

ge_manifest <- files() |>
  filter(cases.project.project_id %in% c('TCGA-OV', "TCGA-BRCA")) |> 
  filter(type == 'slide_image' ) |>
  filter(experimental_strategy == "Diagnostic Slide") |>
  manifest()

names(ge_manifest)
```
Thank you for your help!

**Comment by LiNk-NY** [comment]
Hi Ilaria, @billila 

Thank you for using our software! :smile: 
Unfortunately, the response from the API does not include the `project_id` 
so it requires a separate query using the file names. 
You can add this metadata with `TCGAutils::filenameToBarcode`: 

```r
library(TCGAutils)
packageVersion("TCGAutils")
#' [1] '1.27.4'
metadata <- filenameToBarcode(ge_manifest$file_name, slides = TRUE)
merge(ge_manifest, metadata, by  = "file_name")
```

Best regards,
Marcel
