### ISSUE TITLE
'filters' not defined

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/GenomicDataCommons#24]
R CMD INSTALL GenomicDataCommons
* installing to library ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library’
* installing *source* package ‘GenomicDataCommons’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in namespaceExport(ns, exports) : undefined exports: filters
Error: loading failed
recover called non-interactively; frames dumped, use debugger() to view
* DONE (GenomicDataCommons)

**Comment by seandavi** [comment]
Should be OK now.  Thanks for report.
