### ISSUE TITLE
Need to return more complex object to support counting hits and facets

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/GenomicDataCommons#26]
See #16 for details on facets and the need for this proposed change.

Currently, the API calls return only the "hits" data. To support counting of results (in the pagination JSON object) and facets (in the aggregation JSON object), we need to return a more complicated object.  I am proposing that we return a list with three elements:

- results -- contains the current `gdc_list` representation
- facets -- if facets specified, this will be a list of data.frames, one for each facet field
- pages -- gives counts, page size, and pages

**Comment by seandavi** [comment]
Also, see #15.

**Comment by lawremi** [comment]
Assuming this is happening at a fairly low level, probably should at least slap a class on the list for integrity reasons. See _ListSolrResult_.

**Comment by seandavi** [comment]
That is the thinking. Thanks.

**Comment by seandavi** [comment]
first-pass at complex object complete.  See `GDCResponse`.  Incorporated into tag 0.4.0.
