### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by hsahni** [Bioconductor/GenomicDataCommons#31]
Overall, looks good
Just a few comments
1) For install to work on windows R, l I had to perform the following:

```
source("https://bioconductor.org/biocLite.R")
biocLite("BiocInstaller")
install.packages('devtools')
library(devtools)
install.packages("forecast", repos=c("http://rstudio.org/_packages", "http://cran.rstudio.com"))
devtools::install_github('Bioconductor/GenomicDataCommons')
library(GenomicDataCommons)
```

2) Also `??GenomicDataCommons` did not bring up the Vignettes or the help pages.

**Comment by seandavi** [comment]
Hi, @hsahni.

Could you give the installation on Windows a try now?  I have made a lot of changes, including testing on Windows and things seem to be working.

Sean

**Comment by seandavi** [comment]
I'm going to go ahead and close this, as the windows builds on appveyor appear to be working right now.  

https://ci.appveyor.com/project/seandavi/genomicdatacommons

Feel free to file another issue if you run into more problems.
