### ISSUE TITLE
Link README.md to a vignette

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/GenomicDataCommons#32]
A github trick is to use a symbolic link to connect README.md to a vignette, so that the information in the vignette (available to R users) does  not need to be duplicated to be available to github users. For instance,  at https://github.com/Bioconductor/AnnotationFilter the https://github.com/Bioconductor/AnnotationFilter/blob/master/README is a link to the DESCRIPTION file.

**Comment by seandavi** [comment]
Thanks, @mtmorgan.  Done.
