### ISSUE TITLE
Utilities to rectangularize and tidyize ragged lists

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/GenomicDataCommons#4]

**Comment by lawremi** [comment]
You mean like `stack,List` and `as.data.frame,List` and `as.matrix,List`?

**Comment by seandavi** [comment]
The `purrr` package and the `repurrrsive` packages are an interesting approach to working with lists.

**Comment by seandavi** [comment]
Converted to using `fromJSON` with `simplifyDataFrame=TRUE`.

**Comment by seandavi** [comment]
New method, `as.data.frame.GDCResults` will return a data.frame from any query results.  List columns may be present, but the data structure is a data.frame.
