### ISSUE TITLE
magrittr in Depends field

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/GenomicDataCommons#41]
Hi Sean @seandavi, 
On second thought, it seems like it would be more convenient to keep `magrittr` in the `Depends:`. 
This would avoid all of the `library` calls in the examples. 
Usually, the `Depends:` field is used if the current package extends the that package. 

Taking a quick look at `Organism.dplyr`, @mtmorgan puts `dplyr` in the `Depends` field: 
https://github.com/Bioconductor/Organism.dplyr/blob/master/DESCRIPTION#L16

@mtmorgan Thoughts? 

Also, the tag should be `@importFrom magrittr "%>%"`, at least that worked for me. 

Thanks, 
Marcel

**Comment by LiNk-NY** [comment]
I can run a pull request with the changes.

**Comment by mtmorgan** [comment]
Seems appropriate to have packages in the Depends: field that are needed for the end user to make effective use of the package. I think magrittr fits this bill.
