### ISSUE TITLE
command failed

### ISSUE THREAD

**Issue by changiseng** [Bioconductor/GenomicDataCommons#43]
biocLite('Bioconductor/GenomicDataCommons')

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.25.3), R 3.4.0 (2017-04-21).
Installing github package(s) ‘Bioconductor/GenomicDataCommons’
Downloading GitHub repo Bioconductor/GenomicDataCommons@master
from URL https://api.github.com/repos/Bioconductor/GenomicDataCommons/zipball/master
Installing GenomicDataCommons
"C:/PROGRA~1/R/R-34~1.0/bin/i386/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/User/AppData/Local/Temp/Rtmpe2qcsl/devtools158829604138/Bioconductor-GenomicDataCommons-e10a1d8"  \
  --library="C:/Program Files/R/R-3.4.0/library" --install-tests 

錯誤: Command failed (65535)

Why did not it work?

**Comment by seandavi** [comment]
Hi, @changiseng.

GenomicDataCommons is now in the Bioconductor repository. So, try:

```r
biocLite('GenomicDataCommons')
```

I'll look into what the issue is with the github installation (which is what happens when you install using "Bioconductor/GenomicDataCommons").

**Comment by LiNk-NY** [comment]
@changiseng Please try the command with the latest version of `BiocInstaller` and use the published version of the package as Sean suggested. 
I'm considering this closed. 
Thanks @seandavi. 
Regards,
Marcel
