### ISSUE TITLE
 GDC server down, try to use this package later

### ISSUE THREAD

**Issue by JessieLIII** [Bioconductor/GenomicDataCommons#46]
HI,

I was trying to use TCGAbiolinks. Functions related to GDC gave me the error:
"GDC server down, try to use this package later" for the whole morning.

Any hint what's happening here?

Thanks,
Jessie

**Comment by seandavi** [comment]
Hi, @JessieLIII. 

You can always check `GenomicDataCommons::status()` or go to:

https://gdc-api.nci.nih.gov/status/

A normal response to `status()` will include:

```
$status
[1] "OK"
```

Yes, the GDC server does have extended downtimes at points. Does that help?

**Comment by JessieLIII** [comment]
Thank you!!!


Jiexi Li
Ph.D. Student
Email: Jiexi.Li@uth.tmc.edu

The University of Texas
Graduate School of Biomedical Sciences at Houston




________________________________
