### ISSUE TITLE
What do people think of a functional "builder" API like googlesheets?

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/GenomicDataCommons#5]
https://github.com/jennybc/googlesheets#quick-demo

I could see something like:

projects() %>% filter(....) %>% select(...) %>% limit(10) %>% as.data.frame()

- filter is the equivalent of removing rows (lazy)
- select limits return fields (lazy)
- limit: set start and end on result (lazy)
- as.data.frame(), as.list(), actually executes the query.

Overkill?

**Comment by lawremi** [comment]
Not sure what the pipe has to do with laziness, but sure, that's feasible. See what I did with the rsolr package.

**Comment by seandavi** [comment]
The laziness means that there is no hitting the server until the as.data.frame() [or collect() or whatever].  And, yes, rsolr is a better example.

**Comment by mtmorgan** [comment]
Stepping back, the R user isn't interested in paging as exposed by the API. It seems (to me) like the single function call w/ arguments better captures what the user wants?

**Comment by seandavi** [comment]
That is probably true and certainly more transparent.

**Comment by lawremi** [comment]
How does paging come into this? I guess you could use it to implement a `head` method. But `head`, as a form of reduction, probably does not need to be lazy. It is eager in rsolr.

**Comment by seandavi** [comment]
We can revisit later if needed.  Closing for now.
