### ISSUE TITLE
SSL certificate expiry

### ISSUE THREAD

**Issue by adamp83** [Bioconductor/GenomicDataCommons#59]
Running any command for example `GenomicDataCommons::status()` gives the error

    Error in curl::curl_fetch_memory(url, handle = handle) : 
      SSL certificate problem: certificate has expired

At the command line, running `curl -v -I https://gdc-api.nci.nih.gov/status` output includes:

    * Server certificate:
    *  subject: C=US; postalCode=60305; ST=IL; L=River Forest; street=400 Lathrop Avenue; O=Open Cloud Consortium; OU=PremiumSSL; CN=gdc-api.nci.nih.gov
    *  start date: Jun 18 00:00:00 2015 GMT
    *  expire date: Jun 17 23:59:59 2018 GMT
    *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
    *  SSL certificate verify result: certificate has expired (10), continuing anyway.

Will the certificate be updated soon? If not, is there a workaround? Thanks

**Comment by seandavi** [comment]
I'll do the same, but consider reporting to the GDC folks. I'm traveling today, but I'll check for how to ignore certs in the short term. Thx for the report.

**Comment by allisonheath** [comment]
They have moved over to https://api.gdc.cancer.gov/status - I believe the *.nci.nih.gov URLs are depreciated.

**Comment by seandavi** [comment]
Upgrading to a newer version of GenomicDataCommons will fix the issue. I had missed that you were using an older version that still relied on the previous endpoint URL. Thanks for pointing out that detail.

**Comment by seandavi** [comment]
@allisonheath, thanks for chipping in. I had missed that you were the one dropping the comment.
