### ISSUE TITLE
 GenomicDataCommons::status()

### ISSUE THREAD

**Issue by renhuasong** [Bioconductor/GenomicDataCommons#65]
Hi, 

I have a problem to use the query.met<-GDCquery(project="TCGA-LAML",legacy=TRUE,data.category="DNA methylation",platform="Illumina Human Methylation 450")
Error in value[[3L]](cond) : 
  GDC server down, try to use this package later
In addition, there is an error about GenomicDataCommons::status()
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: gdc-api.nci.nih.gov

sessionInfo() R version 3.4.4 (2018-03-15) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 14.04.5 LTS  Matrix products: default BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0 LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0  locale:  [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8     [6] LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             [11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C         attached base packages:  [1] grid      stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] GenomicDataCommons_1.2.0                 TCGAbiolinks_2.9.5                       DESeq2_1.18.1                             [4] EnsDb.Hsapiens.v86_2.99.0                BiocInstaller_1.28.0                     EnsDb.Mmusculus.v79_2.99.0                [7] ensembldb_2.2.2                          AnnotationFilter_1.2.0                   SummarizedExperiment_1.8.1               [10] DelayedArray_0.4.1                       matrixStats_0.54.0                       VennDiagram_1.6.20                       [13] futile.logger_1.4.3                      tximport_1.6.0                           TxDb.Mmusculus.UCSC.mm10.knownGene_3.4.0 [16] GenomicFeatures_1.30.3                   AnnotationDbi_1.40.0                     Biobase_2.38.0                           [19] gridExtra_2.3                            gtable_0.2.0                             bindrcpp_0.2.2                           [22] forcats_0.3.0                            stringr_1.3.1                            purrr_0.2.5                              [25] readr_1.1.1                              tibble_1.4.2                             tidyverse_1.2.1                          [28] tidyr_0.8.1                              ggpubr_0.1.8                             magrittr_1.5                             [31] dplyr_0.7.6                              reshape_0.8.7                            ggplot2_3.0.0                            [34] rtracklayer_1.38.3                       GenomicRanges_1.30.3                     GenomeInfoDb_1.14.0                      [37] IRanges_2.12.0                           S4Vectors_0.16.0                         BiocGenerics_0.24.0                      [40] limma_3.34.9                              loaded via a namespace (and not attached):   [1] utf8_1.1.4                    R.utils_2.7.0                 tidyselect_0.2.4              htmlwidgets_1.2               RSQLite_2.1.1                   [6] BiocParallel_1.12.0           devtools_1.13.6               DESeq_1.30.0                  munsell_0.5.0                 codetools_0.2-15               [11] withr_2.1.2                   colorspace_1.3-2              knitr_1.20                    rstudioapi_0.7                labeling_0.3                   [16] git2r_0.23.0                  GenomeInfoDbData_1.0.0        hwriter_1.3.2                 KMsurv_0.1-5                  bit64_0.9-7                    [21] rhdf5_2.22.0                  downloader_0.4                lambda.r_1.2.3                ggthemes_4.0.1                EDASeq_2.12.0                  [26] R6_2.2.2                      doParallel_1.0.11             locfit_1.5-9.1                bitops_1.0-6                  assertthat_0.2.0               [31] promises_1.0.1                scales_0.5.0.9000             nnet_7.3-12                   sva_3.26.0                    rlang_0.2.1                    [36] genefilter_1.60.0             cmprsk_2.2-7                  GlobalOptions_0.1.0           splines_3.4.4                 lazyeval_0.2.1                 [41] acepack_1.4.1                 selectr_0.4-1                 checkmate_1.8.5               broom_0.5.0                   yaml_2.2.0                     [46] modelr_0.1.2                  backports_1.1.2               httpuv_1.4.4.1                Hmisc_4.1-1                   RMySQL_0.10.15                 [51] tools_3.4.4                   RColorBrewer_1.1-2            Rcpp_0.12.18                  plyr_1.8.4                    base64enc_0.1-3                [56] progress_1.2.0                zlibbioc_1.24.0               RCurl_1.95-4.11               prettyunits_1.0.2             rpart_4.1-13                   [61] GetoptLong_0.1.7              cowplot_0.9.3                 zoo_1.8-3                     haven_1.1.2                   ggrepel_0.8.0                  [66] cluster_2.0.7-1               data.table_1.11.4             futile.options_1.0.1          circlize_0.4.4                survminer_0.4.3                [71] ProtGenerics_1.10.0           aroma.light_3.8.0             hms_0.4.2                     mime_0.5                      xtable_1.8-3                   [76] XML_3.98-1.16                 readxl_1.1.0                  shape_1.4.4                   compiler_3.4.4                biomaRt_2.34.2                 [81] crayon_1.3.4                  R.oo_1.22.0                   htmltools_0.3.6               mgcv_1.8-24                   later_0.7.4                    [86] Formula_1.2-3                 geneplotter_1.56.0            lubridate_1.7.4               DBI_1.0.0                     formatR_1.5                    [91] matlab_1.0.2                  ComplexHeatmap_1.17.1         ShortRead_1.36.1              Matrix_1.2-14                 cli_1.0.0                      [96] R.methodsS3_1.7.1             bindr_0.1.1                   pkgconfig_2.0.2               km.ci_0.5-2                   GenomicAlignments_1.14.2      [101] foreign_0.8-71                xml2_1.2.0                    foreach_1.4.4                 annotate_1.56.2               XVector_0.18.0                [106] rvest_0.3.2                   digest_0.6.17                 ConsensusClusterPlus_1.42.0   Biostrings_2.46.0             cellranger_1.1.0              [111] htmlTable_1.12                survMisc_0.5.5                edgeR_3.20.9                  curl_3.2                      shiny_1.1.0                   [116] Rsamtools_1.30.0              rjson_0.2.20                  nlme_3.1-137                  jsonlite_1.5                  fansi_0.3.0                   [121] pillar_1.3.0                  lattice_0.20-35               httr_1.3.1                    survival_2.42-3               interactiveDisplayBase_1.16.0 [126] glue_1.3.0                    iterators_1.0.10              bit_1.1-14                    stringi_1.2.3                 blob_1.1.1                    [131] AnnotationHub_2.10.1          latticeExtra_0.6-28           memoise_1.1.0
--
 
  |  
 

How can I solve the problem? Thanks a lot.

**Comment by brisk022** [comment]
The old api URL no longer redirects. You need to upgrade GenomicDataCommons to version 1.4 or above.

Alternatively, if you need to stay with your installed version (v1.2), you can download the source from [Bioconductor](https://www.bioconductor.org/packages/3.6/bioc/src/contrib/GenomicDataCommons_1.2.0.tar.gz), change the URL in R/constants.R (.gdc_base on the first line) from "https://gdc-api.nci.nih.gov" to "https://api.gdc.cancer.gov", and re-install from the updated source using `devtools::install_local(<sourceDir>, force = T)`.

**Comment by seandavi** [comment]
Thanks, @brisk022. Upgrading R, Bioconductor, and GenomicDataCommons is, indeed, the way to go.
