### ISSUE TITLE
Download Fails if File In Legacy Archive

### ISSUE THREAD

**Issue by DarioS** [Bioconductor/GenomicDataCommons#72]
Some files were never harmonised and made available in the new data portal. One example is whole genome DNA sequencing, which is only available from Legacy Archive. The download fails with an error.

```r
> gdcdata("62f53214-e1e5-42fe-821b-a2a656206e1f", token=T)
Error: '{"data": {"hits": [], "pagination": {"count": 0, "sort": "", "from": 0, "pages": 0, "total": 0, "page": 0, "size": 0}}, "warnings": {}}' does not exist in current working directory
```

Can this be made possible in the next version?

**Comment by LiNk-NY** [comment]
resolved in https://github.com/Bioconductor/GenomicDataCommons/pull/84
