### ISSUE TITLE
Error in gdc_token() : file.exists(token_file) is not TRUE

### ISSUE THREAD

**Issue by SisiChen16** [Bioconductor/GenomicDataCommons#90]
I was trying to get token authentication, I managed to download a token as "txt" file, and tried the three ways of gdc_token as below, but none of them worked. The error message keeps popping up, as "Error in gdc_token(): file.exists(token_file) is not TRUE", I don't know what to do. 
1. As a string stored in the environment variable, GDC_TOKEN
2. As a file, stored in the file named by the environment variable, GDC_TOKEN_FILE
3. In a file in the user home directory, called .gdc_token

**Comment by LiNk-NY** [comment]
Hi @SisiChen16 

Please make sure that the path to the token is correct. 

Within the R session, you can check if the environment variable is specified using
 `Sys.getenv("GDC_TOKEN")`. 

You can add the contents of the token within the `~/.Renviron` file as `GDC_TOKEN="token_text"`
and then check using the code above. 

I don't see an issue with the code. 

Best regards,
Marcel

**Comment by SisiChen16** [comment]
Hi Marcel, 

The problem has been solved, thank you so much! 

Best wishes, 
Sisi

**Comment by seandavi** [comment]
@SisiChen16, I think the last piece was a bug. See #91. Should be fixed in 1.19.3 now on github if you want to try it.
